easy_admin:
  site_name: 'TravelGroup'
  entities:
#        # List the entity class name you want to manage
    User:
      class: App\Entity\User
      list:
        fields: ['username', 'email', 'enabled', 'lastLogin']
    Voyage:
      class: App\Entity\Voyage
    Activite:
      class: App\Entity\Activite

  design:
    assets:
      css:
        - 'bundles/easyadmin/bootstrap-all.css'
      js:
        - 'bundles/easyadmin/bootstrap-all.js'
